package.json
=> Patch update: v0.0.3

package.json
`v0.0.0` - Add Casts related methods
`v0.1.0` - Add Follow related methods
`v0.2.0` - Add User related methods
`v0.3.0` - Add Verification related methods
`v0.3.1` - Fix versions appropriately
=> Set version appropriately along with development timeline

package.json, src/neynar-api/neynar-v1-api/neynar-api-v1-client.ts, src/neynar-api/neynar-v1-api/openapi/apis/follows-api.ts, src/neynar-api/neynar-v1-api/openapi/models/follow-response-result.ts, tsconfig.json
- Update Followers and Following methods to incorporate pagination in them.
=> Update Followers and Following methods to incorporate pagination in them.

src/neynar-api/neynar-v2-api/neynar-api-v2-client.ts
Send Success ack after deleting cast
=> Send Success ack after deleting cast

package.json, src/neynar-api/neynar-v2-api/neynar-api-v2-client.ts, src/neynar-api/neynar-v2-api/openapi-farcaster/apis/cast-api.ts, src/neynar-api/neynar-v2-api/openapi-farcaster/apis/user-api.ts
Add user apis
- removeVerification
- addVerification
- followUser
- unfollowUser
- updateUserProfile
- fetchUsersInBulk
- searchUser
=> Add user apis

package.json, src/neynar-api/neynar-api-client.ts, src/neynar-api/neynar-v2-api/neynar-api-v2-client.ts
=> Combine V1 client and V2 client

src/neynar-api/neynar-api-client.ts, src/neynar-api/neynar-v1-api/neynar-api-v1-client.ts, src/neynar-api/neynar-v2-api/neynar-api-v2-client.ts
=> Remove duplicate code

src/neynar-api/neynar-api-client.ts, src/neynar-api/neynar-v2-api/neynar-api-v2-client.ts, src/neynar-api/neynar-v2-api/openapi-farcaster/apis/feed-api.ts
- Add filter type `global_trending` in feed API
- Make `fid` optional and `feedType` required in feed API
=> Sync sdk with oas

src/neynar-api/utils/v1-to-v2-converters.ts
Add initiallize empty verified_addresses in convertToV2User
=> Add initiallize empty verified_addresses in convertToV2User

package.json, src/neynar-api/common/constants.ts, src/neynar-api/neynar-api-client.ts, src/neynar-api/v2/client.ts, src/neynar-api/v2/openapi-farcaster/apis/feed-api.ts, src/neynar-api/v2/openapi-farcaster/models/frame-action.ts, src/neynar-api/v2/openapi-farcaster/models/webhook-subscription-filters-cast-created.ts
**New Methods**
**Feed**
- fetchTrendingFeed -> https://docs.neynar.com/reference/feed-trending
**Removes `withReplies` param from**
- feed -> https://docs.neynar.com/reference/feed
- feedFollowing -> https://docs.neynar.com/reference/feed-following
**Adds**
- `text` in WebhookSubscriptionFiltersCastCreated Interface
- `address` in FrameAction Interface
=> Add fetchTrendingFeed and remove with replies

package.json, src/neynar-api/neynar-api-client.ts, src/neynar-api/v2/client.ts, src/neynar-api/v2/openapi-farcaster/apis/channel-api.ts, src/neynar-api/v2/openapi-farcaster/apis/reaction-api.ts, src/neynar-api/v2/openapi-farcaster/apis/user-api.ts, src/neynar-api/v2/openapi-farcaster/models/channel.ts
New Method
User
fetchUserChannels -> https://docs.neynar.com/reference/user-channels
Updates Existing Methods
Reaction
fetchReactionsForCast -> https://docs.neynar.com/reference/reactions-cast
- types is now an array of ReactionsType, we join the array into a string at the end.
misc
Feed
fetchTrendingChannels -> https://docs.neynar.com/reference/trending-channels fixed limit
=> adds fetchUserChannels, updates fetchReactionsForCast types parameter, and depreciates limit notes for fetchTrendingChannels

package.json, src/neynar-api/v2/openapi-farcaster/models/frame-state.ts, src/neynar-api/v2/openapi-farcaster/models/frame.ts
=> Update Frame schema

package.json, src/neynar-api/v2/openapi-farcaster/models/user.ts
Add power_badge in User interface
=> Add power_badge in User interface

src/neynar-api/utils/v1-to-v2-converters.ts
Ignore ts warning for v1 to v2 user, since v1 wont have powerbadge
=> Ignore ts warning for v1 to v2 user, since v1 wont have powerBadge

package.json, src/neynar-api/common/version.ts, src/neynar-api/neynar-api-client.ts, src/neynar-api/v2/client.ts, src/neynar-api/v2/openapi-farcaster/apis/cast-api.ts
methods updates:
lookUpCastByHashOrWarpcastUrl -> https://docs.neynar.com/reference/cast
- now takes in a viewerFid parameter
lookupCastConversation -> https://docs.neynar.com/reference/cast-conversation
- now takes in a viewerFid parameter
=> adds viewer fid to conversation and cast methods

package.json, src/neynar-api/common/version.ts, src/neynar-api/neynar-api-client.ts, src/neynar-api/v2/client.ts, src/neynar-api/v2/openapi-farcaster/apis/user-api.ts
Updates:
fetchBulkUsersByEthereumAddress -> https://docs.neynar.com/reference/user-bulk-by-address
- now takes in a viewer fid
=> add bulk by address sdk changes

package.json, src/neynar-api/common/version.ts, src/neynar-api/neynar-api-client.ts, src/neynar-api/v2/client.ts, src/neynar-api/v2/openapi-farcaster/apis/channel-api.ts, src/neynar-api/v2/openapi-farcaster/apis/feed-api.ts
Updates
fetchFeedByChannelIds -> https://docs.neynar.com/reference/feed-channels:
now takes in optional shouldModerate parameter
misc:
channelDetailsBulk summary updated
=> fetch feed now takes in should moderate

package.json, src/neynar-api/common/version.ts, src/neynar-api/v2/openapi-farcaster/apis/user-api.ts, src/neynar-api/v2/openapi-farcaster/models/channel.ts
misc:
the Channel type now has a property moderator
=> the Channel type now has a property moderator

package.json, src/neynar-api/common/version.ts, src/neynar-api/neynar-api-client.ts, src/neynar-api/v2/client.ts, src/neynar-api/v2/openapi-farcaster/apis/user-api.ts
updates
fetchPowerUsers -> https://docs.neynar.com/reference/power-users
now has a optional viewerFid parameter
=> fetchPowerUsers now has a viewerFid parameter

package.json, src/neynar-api/common/version.ts, src/neynar-api/v2/openapi-farcaster/models/follow-response.ts, src/neynar-api/v2/openapi-farcaster/models/webhook-subscription-filters-cast-created.ts
Please don't merge this PR
Need to merge OAS PR https://github.com/neynarxyz/OAS/pull/150 first and then need to update and commit the submodule in this PR
=> Add exclude_author_fids in webhook subscription filters

src/neynar-api/v2/openapi-farcaster/.openapi-generator/FILES, src/neynar-api/v2/openapi-farcaster/apis/feed-api.ts, src/neynar-api/v2/openapi-farcaster/models/embed-url-metadata.ts, src/neynar-api/v2/openapi-farcaster/models/embedded-cast.ts, src/neynar-api/v2/openapi-farcaster/models/index.ts
Again this also includes someone else's OAS changes that apparently didn't get regenerated in here.
Counterpart to
- https://github.com/neynarxyz/api/pull/592
- https://github.com/neynarxyz/OAS/pull/154
=> Add EmbedUrlMetadata optional subobject to EmbedUrl [NEYN-2116]

package.json, src/neynar-api/common/version.ts, src/neynar-api/v2/openapi-farcaster/models/subscribed-to-object.ts
Changes
- SubscribedToObject  type now has protocol_version
=> add protocol_version to subscribers response

package.json, src/neynar-api/common/version.ts, src/neynar-api/v2/openapi-farcaster/models/channel.ts
Introduce moderator_fids and member_count in Channel model
=> Introduce moderator_fids and member_count in Channel interface

package.json, src/neynar-api/common/version.ts
=> Minor update: v1.60.0

package.json, src/neynar-api/common/version.ts
=> minor update: v1.61.0

docs/CONTRIBUTING.md
Update process for creating releases with more active contributions
=> docs: update contribution guide

package.json, src/neynar-api/common/version.ts
=> Minor update: v1.63.0

package.json, src/neynar-api/common/version.ts
Breaking changes:
- `EmbeddedCast` type renamed to `Embed`
- `EmbedCastId` type renamed to `EmbedCast`
=> Minor update: v1.65.0

src/neynar-api/utils/v1-to-v2-converters.ts, src/neynar-api/v2/openapi-farcaster/apis/action-api.ts, src/neynar-api/v2/openapi-farcaster/apis/ban-api.ts, src/neynar-api/v2/openapi-farcaster/apis/block-api.ts, src/neynar-api/v2/openapi-farcaster/apis/cast-api.ts, src/neynar-api/v2/openapi-farcaster/apis/channel-api.ts, src/neynar-api/v2/openapi-farcaster/apis/feed-api.ts, src/neynar-api/v2/openapi-farcaster/apis/fname-api.ts, src/neynar-api/v2/openapi-farcaster/apis/follows-api.ts, src/neynar-api/v2/openapi-farcaster/apis/frame-api.ts, src/neynar-api/v2/openapi-farcaster/apis/mute-api.ts, src/neynar-api/v2/openapi-farcaster/apis/notifications-api.ts, src/neynar-api/v2/openapi-farcaster/apis/reaction-api.ts, src/neynar-api/v2/openapi-farcaster/apis/signer-api.ts, src/neynar-api/v2/openapi-farcaster/apis/storage-api.ts, src/neynar-api/v2/openapi-farcaster/apis/subscribers-api.ts, src/neynar-api/v2/openapi-farcaster/apis/user-api.ts, src/neynar-api/v2/openapi-farcaster/apis/webhook-api.ts
Changes to wording of docstrings.
Plus fixes a build issue.
=> doc: improve wording of documentation

package.json, src/neynar-api/common/version.ts, src/neynar-api/neynar-api-client.ts, src/neynar-api/v2/client.ts, src/neynar-api/v2/openapi-farcaster/apis/user-api.ts
Adds `fetchUsersByLocation` method to get users by location.
```
const result = await client.fetchUsersByLocation(34.05, -118.24, {limit: 3});
console.log(JSON.stringify(result));
```
```
$  node index.js | jq '.users[] | {fid: .fid, username: .username, profile: .profile}'
{
"fid": 2,
"username": "v",
"profile": {
"bio": {
"text": "Technowatermelon. Elder Millenial. Building Farcaster. \n\nnf.td/varun"
},
"location": {
"latitude": 34.05,
"longitude": -118.24,
"address": {
"city": "Los Angeles",
"state": "California",
"state_code": "ca",
"country": "United States of America",
"country_code": "us"
}
}
}
}
{
"fid": 3,
"username": "dwr.eth",
"profile": {
"bio": {
"text": "Working on Farcaster and Warpcast."
},
"location": {
"latitude": 34.05,
"longitude": -118.24,
"address": {
"city": "Los …
```
=> feat: search users by location
